export const lessons=[
{title:'Stop giving pieces away',theme:'Board vision',level:0,range:'FOUNDATIONS',intro:'Your first improvement is making every piece harder to win.',text:['Before moving, ask what changed on the last move. A bishop may have opened a diagonal; a queen may now attack two pieces.','Check the square you intend to use. Count attackers and defenders, but also compare their values: pawn 1, knight or bishop about 3, rook 5, queen 9. A defended pawn is not necessarily safe for your queen to capture.','After choosing a move, imagine the opponent taking your most valuable exposed piece. If that works, look for a safer move.'],rule:'What can my opponent take after this move?'},
{title:'Recognise the mating net',theme:'King safety',level:0,range:'FOUNDATIONS',intro:'Checks matter when the king has nowhere useful to go.',text:['A check forces an answer: capture the attacker, block the line, or move the king. Knight checks cannot be blocked.','For back-rank mates, pawns imprison their own king. A rook or queen can finish the game if no defender can intervene.','Always check every legal escape square. An attractive check is not checkmate if the king can capture the checking piece.'],rule:'Can the king capture, block, or escape?'},
{title:'Win two targets at once',theme:'Tactics',level:1,range:'BUILD YOUR PATTERNS',intro:'A forcing threat buys time for the second attack.',text:['A fork attacks two targets. A knight fork with check is particularly forcing because the king must respond first.','A pin discourages or prevents a defender from moving. If moving exposes the king to check, the pinned move is illegal.','Scan for loose pieces on the same rank, file or diagonal. Before starting a combination, check whether your attacking piece can simply be taken.'],rule:'Which two targets can one move attack?'},
{title:'Get out of the opening',theme:'Opening habits',level:1,range:'BUILD YOUR PATTERNS',intro:'Aim for a playable position you understand.',text:['Fight for the centre, develop your minor pieces and bring your king to safety. These are guides; immediate threats take priority.','Moving the same piece repeatedly gives your opponent time to develop. Early queen adventures often give the opponent useful moves with tempo.','Watch f2 and f7: initially only the king defends them. If your opponent brings out the queen and bishop, calculate the threat before making a routine developing move.'],rule:'What is the threat, and can I develop while meeting it?'},
{title:'Calculate the reply',theme:'Calculation',level:2,range:'THINK AHEAD',intro:'A combination is only as good as the opponent’s best defence.',text:['Choose two or three candidate moves. Start with forcing checks and captures, then consider direct threats.','For each candidate, find the strongest reply for the opponent. Do not assume they take the bait. Continue until you reach a position you can assess.','Compare the resulting positions, then do one final blunder check on the move you choose. Take the full time available rather than guessing from a familiar pattern.'],rule:'My move, their best reply, my next move.'},
{title:'Convert the advantage',theme:'Endgames',level:1,range:'FINISH THE JOB',intro:'Winning material is only the beginning.',text:['In a safe endgame, activate your king. It can help escort passed pawns and restrict the opposing king.','With king and rook against king, use the rook to reduce the available space, then bring your king closer. Keep your rook far enough away that it cannot be captured.','With a queen, keep checking for stalemate. If the opponent is not in check and has no legal move, the game is drawn.'],rule:'Improve my king, restrict theirs, avoid stalemate.'},
{title:'Turn games into training',theme:'Personal mistakes',level:2,range:'THE 1500 HABIT',intro:'Your own games reveal what to practise next.',text:['Play a serious rapid game with time to think. Record the moments where you were uncertain before checking an engine.','Import the PGN in Review a game and choose your colour. The app saves significant missed opportunities as personal exercises. Engine evaluations are estimates, not a complete explanation of the position.','Return to the saved positions without looking at the answer. Explain the threat to yourself, play your move, then check the continuation.'],rule:'One game, one useful lesson, one position to revisit.'},
{title:'Build a repeatable routine',theme:'Calculation',level:3,range:'BEYOND THE BASICS',intro:'Consistency is more useful than a one-off puzzle marathon.',text:['Complete a short session most days. Prioritise due mistakes, then practise your weakest pattern. Use hints to learn, but solve without hints before calling a position mastered.','Mix training with rated rapid games. Log your actual rating in Progress using one platform and time control so comparisons mean something.','When improvement slows, inspect your losses: time pressure, opening confusion and endgame errors need different remedies. An app cannot guarantee a rating; use the evidence from your games to guide the next week.'],rule:'Train a weakness, test it in a game, review the result.'}
];
