// Tag, rate and publish the puzzle set to data/puzzles.js.
//
//   node tools/build-puzzles.mjs              # starter + generated (or Lichess if imported)
//   node tools/build-puzzles.mjs --source generated|lichess|both
//
// Inputs live in tools/data: starter.json (hand-picked set), generated-raw.jsonl
// (from generate-puzzles.mjs) and lichess.json (from import-lichess.mjs).
import fs from 'node:fs';
import crypto from 'node:crypto';
import { Chess } from '../vendor/chess.js';
import { analyseLine, explainLine } from '../src/tagger.js';
import { primaryTheme, displayTags } from '../src/themes.js';
import { estimateRating } from '../src/difficulty.js';
import { playUci } from '../src/chess-utils.js';

const DATA = new URL('./data/', import.meta.url);
const read = name => (fs.existsSync(new URL(name, DATA)) ? fs.readFileSync(new URL(name, DATA), 'utf8') : null);

export function goalFor(tags, line) {
  const n = Math.ceil(line.length / 2);
  if (tags.includes('mate')) return n === 1 ? 'Deliver checkmate in one.' : `Deliver checkmate in ${n}.`;
  if (tags.includes('hangingPiece')) return 'Win material.';
  if (tags.includes('promotion')) return 'Find the winning continuation.';
  return n === 1 ? 'Find the strongest move.' : 'Find the winning continuation.';
}

function startPosition(fen, setup) {
  const g = new Chess(fen);
  if (setup) playUci(g, setup);
  return g;
}

export function finalize(raw) {
  const start = startPosition(raw.fen, raw.setup);
  const analysed = analyseLine(raw.fen, raw.line, { score: raw.score ?? null, setup: raw.setup || null });
  const tags = raw.tags?.length ? raw.tags : analysed.tags;
  const theme = raw.theme || primaryTheme(tags);
  const firstSan = analysed.facts.first?.san || '';
  const rating =
    raw.rating || estimateRating({ tags, line: raw.line, discovery: raw.discovery, legalMoves: start.moves().length, firstSan });
  const out = {
    id: raw.id,
    title: raw.title || displayTags(tags, 1)[0] || (theme === 'Tactics' ? 'Winning move' : theme),
    fen: raw.fen,
    ...(raw.setup ? { setup: raw.setup } : {}),
    line: raw.line,
    theme,
    tags,
    rating,
    goal: goalFor(tags, raw.line),
    explanation: raw.explanation || explainLine(raw.fen, raw.line, { setup: raw.setup || null }),
    source: raw.source,
    ...(raw.lichessId ? { lichessId: raw.lichessId } : {}),
  };
  return out;
}

export function stableId(prefix, raw) {
  return (
    prefix +
    crypto
      .createHash('sha1')
      .update(raw.fen + '|' + (raw.setup || ''))
      .digest('hex')
      .slice(0, 8)
  );
}

/** Keep the set varied: cap mates and very similar positions. */
export function balance(list, { mateShare = 0.35 } = {}) {
  const mates = list.filter(p => p.tags.includes('mate'));
  const others = list.filter(p => !p.tags.includes('mate'));
  const maxMates = Math.round((others.length * mateShare) / (1 - mateShare));
  // Prefer the more varied mates: longer ones and special patterns first.
  const score = p => (p.tags.includes('mateIn1') ? 0 : 1) + (p.tags.includes('backRankMate') || p.tags.includes('smotheredMate') ? 1 : 0);
  const keptMates = mates.sort((a, b) => score(b) - score(a) || a.id.localeCompare(b.id)).slice(0, maxMates);
  return [...others, ...keptMates];
}

export function serialise(puzzles) {
  return (
    '// Generated by tools/build-puzzles.mjs. Do not edit by hand.\n' +
    '// Sources and licences: see THIRD-PARTY.md.\n' +
    'export const puzzles = [\n' +
    puzzles.map(p => JSON.stringify(p)).join(',\n') +
    '\n];\n'
  );
}

function main() {
  const args = process.argv.slice(2);
  const sourceArg = args.includes('--source') ? args[args.indexOf('--source') + 1] : null;
  const lichessRaw = read('lichess.json');
  const source = sourceArg || (lichessRaw ? 'lichess' : 'generated');

  const starter = JSON.parse(read('starter.json')).map(p => finalize({ ...p, source: 'starter' }));
  let pool = [];
  if (source === 'generated' || source === 'both') {
    const seen = new Set();
    for (const line of (read('generated-raw.jsonl') || '').split('\n')) {
      if (!line.trim()) continue;
      const raw = JSON.parse(line);
      const id = stableId('g', raw);
      if (seen.has(id)) continue;
      seen.add(id);
      try {
        pool.push(finalize({ ...raw, id, source: 'generated' }));
      } catch (e) {
        console.warn('skip', id, e.message);
      }
    }
    pool = balance(pool);
  }
  if (source === 'lichess' || source === 'both') {
    if (!lichessRaw) throw new Error('No tools/data/lichess.json. Run tools/import-lichess.mjs first.');
    for (const raw of JSON.parse(lichessRaw)) pool.push(finalize({ ...raw, id: 'l' + raw.lichessId, source: 'lichess' }));
  }
  pool.sort((a, b) => a.rating - b.rating || a.id.localeCompare(b.id));
  const all = [...starter, ...pool];
  fs.writeFileSync(new URL('../data/puzzles.js', import.meta.url), serialise(all));
  const byTheme = {};
  for (const p of all) byTheme[p.theme] = (byTheme[p.theme] || 0) + 1;
  console.log(`Wrote ${all.length} puzzles (${starter.length} starter, ${pool.length} ${source}).`, byTheme);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
